// Layer 6/8 — grid effects (EXACT interface). Generic Fantasy defaults.
import type { GridEffectEntry } from '../types';

export const gridEffects: GridEffectEntry[] = [
  {
    id: 'connection-cell-pop',
    name: 'Connection cell pop + glow',
    description:
      'Per-cell win juice for the cells of ONE winning connection, played in parallel across the group: dip → pop overshoot + glow flare + additive shockwave ring + warm flash + rotation wobble + dark backdrop → settle → hold → reset to idle.',
    version: '1.0.0',
    implemented: true,
    trigger: 'any win',
    scope: 'specific-cells',
    duration: 0.91,
    intensity: 'strong',
    cancellable: true,
    style: { colors: [0xfff0cf], blend: 'add' },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
  {
    id: 'win-shockwave-ring',
    name: 'Win shockwave ring',
    description:
      'On each winning cell an additive ring expands from ~0.85×cell to 1.95×cell while fading to 0 over ~330ms.',
    version: '1.0.0',
    implemented: true,
    trigger: 'any win (per winning cell)',
    scope: 'specific-cells',
    duration: 0.33,
    intensity: 'medium',
    style: { blend: 'add' },
    params: { startScale: 0.85, endScale: 1.95 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
  {
    id: 'scatter-orbit-light',
    name: 'Scatter orbit light',
    description:
      'Two additive comet sprites orbit a landed scatter on R≈0.48×cell behind a faint additive track ring, full rotation ~820ms, looping until the FS-trigger burst. Per scatter cell.',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatterCount >= 2 (per landed scatter cell)',
    scope: 'specific-cells',
    duration: 0.82,
    intensity: 'medium',
    loop: true,
    cancellable: true,
    style: { colors: [0xffe168], blend: 'add' },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
  {
    id: 'police-lights',
    name: 'Police lights (alternating wash)',
    description:
      'Two large additive radial glows (left/right of the grid) alternate alpha 0.6↔0.12 every ~230ms for the anticipation siren mood. Full-grid wash, fades on stop.',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatterCount >= 2 (anticipation active)',
    scope: 'full-grid',
    duration: 0.23,
    intensity: 'strong',
    loop: true,
    cancellable: true,
    style: { colors: [0xff3030, 0x4076ff], blend: 'add' },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
  {
    id: 'sweat-column-highlight',
    name: 'Sweat column highlight',
    description:
      'Per pending reel: dark dim strip under a warm additive glow strip under a gold frame. The active (currently dropping) reel pulses brighter. Marks "here the next scatter could fall".',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatterCount >= 2 (per pending reel)',
    scope: 'reel',
    duration: 0.6,
    intensity: 'strong',
    loop: true,
    cancellable: true,
    style: { colors: [0xffd633], blend: 'normal' },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
  {
    id: 'fs-transition-spin-out',
    name: 'Free Spins transition — spin/shrink out',
    description:
      'Whole grid pivots about its center: rotation 0→2.5 turns, scale 1→0.02, alpha 1→0 over ~600ms, then board cleared.',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatterCount >= 3 (free spins triggered)',
    scope: 'full-grid',
    duration: 0.6,
    intensity: 'strong',
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
  {
    id: 'fs-transition-spin-in',
    name: 'Free Spins transition — spin/scale in',
    description: 'Restore: grid from rotation −2π / scale 0.05 / alpha 0 back to identity over ~520ms.',
    version: '1.0.0',
    implemented: true,
    trigger: 'free spins start (restore)',
    scope: 'full-grid',
    duration: 0.52,
    intensity: 'strong',
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways'],
  },
];
