// Layer 11 — sound cues. Procedural Web-Audio synth (no asset files needed),
// one entry per event in the Fantasy audio manifest (public/audio/manifest.json).
import type { SoundEventEntry } from '../types';

export const soundEvents: SoundEventEntry[] = [
  {
    id: 'spin-start',
    name: 'Spin Start',
    description: 'Short whoosh when the reels begin spinning.',
    version: '1.0.0',
    implemented: true,
    trigger: 'spin button click',
    loop: false,
    volume: 0.5,
    synth: { type: 'sweep', freq: 220, freqTo: 660, durationMs: 180 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'reel-stop',
    name: 'Reel Stop',
    description: 'Thud/click when each reel lands (×5 per spin, staggered).',
    version: '1.0.0',
    implemented: true,
    trigger: 'each reel landing',
    loop: false,
    volume: 0.6,
    synth: { type: 'thud', freq: 140, durationMs: 90 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'reel-spin-loop',
    name: 'Reel Spin Loop',
    description: 'Looping mechanical whir while reels are in motion.',
    version: '1.0.0',
    implemented: true,
    trigger: 'reels spinning',
    loop: true,
    volume: 0.4,
    synth: { type: 'noise', durationMs: 400 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'win-connect-sound',
    name: 'Win Connect (rising)',
    description: 'Rising "connect" chime per sequential-reveal step (pitch steps up per index).',
    version: '1.0.0',
    implemented: true,
    trigger: 'per win connection',
    loop: false,
    volume: 0.6,
    synth: { type: 'chime', freq: 520, durationMs: 160 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'win-small',
    name: 'Small Win',
    description: 'Brief chime for wins under 2× bet.',
    version: '1.0.0',
    implemented: true,
    trigger: 'win < 2x bet',
    loop: false,
    volume: 0.7,
    synth: { type: 'chime', freq: 660, durationMs: 220 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'win-normal',
    name: 'Normal Win',
    description: 'Mid-tier chime for wins 2×–10× bet.',
    version: '1.0.0',
    implemented: true,
    trigger: 'win 2x-10x bet',
    loop: false,
    volume: 0.7,
    synth: { type: 'chime', freq: 784, durationMs: 300 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'win-big',
    name: 'Big Win',
    description: 'Escalating fanfare for wins 10×–50× bet.',
    version: '1.0.0',
    implemented: true,
    trigger: 'win 10x-50x bet',
    loop: false,
    volume: 0.85,
    synth: { type: 'riser', freq: 440, freqTo: 1320, durationMs: 900 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'win-mega',
    name: 'Mega Win',
    description: 'Epic celebration for wins 50×+ bet.',
    version: '1.0.0',
    implemented: true,
    trigger: 'win >= 50x bet',
    loop: false,
    volume: 0.95,
    synth: { type: 'riser', freq: 523, freqTo: 1760, durationMs: 1400 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'scatter-land',
    name: 'Scatter Land',
    description: 'Distinctive sound when a scatter becomes visible.',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatter visible on reel stop',
    loop: false,
    volume: 0.7,
    synth: { type: 'chime', freq: 880, durationMs: 260 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'near-miss-tease',
    name: 'Near-Miss Tease',
    description: 'Rising tension tone when a reel enters its near-miss slowdown.',
    version: '1.0.0',
    implemented: true,
    trigger: 'reel entering near-miss deceleration',
    loop: false,
    volume: 0.7,
    synth: { type: 'riser', freq: 200, freqTo: 520, durationMs: 700 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'free-spin-trigger',
    name: 'Free Spin Trigger',
    description: 'Triumphant sound when 3+ scatters trigger the bonus.',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatterCount >= 3',
    loop: false,
    volume: 0.9,
    synth: { type: 'riser', freq: 392, freqTo: 1568, durationMs: 1100 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'coin-chime',
    name: 'Coin Chime',
    description: 'Short coin impact accent during big+ win / Hold & Win celebrations.',
    version: '1.0.0',
    implemented: true,
    trigger: 'big/mega celebration / coin lock',
    loop: false,
    volume: 0.7,
    synth: { type: 'chime', freq: 1046, durationMs: 140 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'siren-loop',
    name: 'Anticipation Siren',
    description: 'Looping siren wash during the scatter sweat / police-lights anticipation.',
    version: '1.0.0',
    implemented: true,
    trigger: 'scatterCount >= 2 anticipation',
    loop: true,
    volume: 0.4,
    synth: { type: 'siren', freq: 480, freqTo: 720, durationMs: 800 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
  {
    id: 'ambient-music',
    name: 'Background Music',
    description: 'Looping ambient bed during gameplay.',
    version: '1.0.0',
    implemented: false, // off by default in the preview (procedural bed is optional)
    trigger: 'game load',
    loop: true,
    volume: 0.35,
    synth: { type: 'tone', freq: 110, durationMs: 2000 },
    compatibleGrids: ['5x5', '5x3'],
    compatibleModels: ['ways', 'payline'],
  },
];
